name: primeira-pipeline
on: 
  push:
    branches: ["main"]
  workflow_dispatch: #Permite que execute manualmente
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest ##similar ao gitlab-runner
    steps: #aqui entram as actions
      - name: "Minha primeira ação"
        run: echo "Hello World!!!"
      - name: "Minha segunda ação"
        run: | # pode ser executado um comando direto ou coloca-se um pipe e vários comandos abaixo
          echo "Você criou o seu primeiro workflow!!!"
          echo "Parabéns!!!"
      - name: "Script Python"
        run: |
          variavel = "Hello World!!!"
          print(variavel)
        shell: python
  segundo-job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
      - name: "Definindo verão específica (22.9.0) do NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
      - name: "Verificação da versão do NodeJS depois de especificar"
        run: node --version
          





      
      
    
  
